"""
export/pdf_report.py — PDF report generation using ReportLab.
"""

import time
from datetime import datetime
from xml.sax.saxutils import escape as xml_escape

import numpy as np
import pandas as pd

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, PageBreak, Image, Preformatted,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from pathlib import Path

from core.config import state
from core.metrics import get_score_label
from charts.plots import (
    plot_dashboard, plot_distribution, plot_model_comparison,
    plot_framework_comparison_bars, plot_framework_ragking_bars,
    plot_framework_spider, plot_framework_box,
    rl_score_color,
)
from ui.helpers import ok, err, info


REPORT_TEXT = {
    "en": {
        "title":              "RAG EVALUATION REPORT",
        "subtitle":           "RAGking v2.1 - Ranking & Evaluation System",
        "generated":          "Generated",
        "overall":            "OVERALL RAG SYSTEM SCORE",
        "interpretation":     "Interpretation",
        "metrics":            "KEY METRICS SUMMARY",
        "metric":             "Metric",
        "value":              "Value",
        "observation":        "Observation",
        "samples":            "Samples Evaluated",
        "correctness_avg":    "Average Correctness",
        "latency_avg":        "Average Latency",
        "token_eff":          "Token Efficiency",
        "prompt_tokens_avg":  "Avg Prompt Tokens",
        "completion_tokens_avg": "Avg Completion Tokens",
        "total_tokens_avg":   "Avg Total Tokens",
        "sim_avg":            "Avg Semantic Similarity",
        "fail_rate":          "Failure Rate",
        "std":                "Std Dev (RAGking)",
        "system_config":      "SYSTEM CONFIGURATION",
        "parameter":          "Parameter",
        "where":              "Where",
        "analysis":           "ANALYSIS & RECOMMENDATIONS",
        "strengths":          "Strengths",
        "improvements":       "Areas for Improvement",
        "recommendations":    "Actionable Recommendations",
        "report_footer":      "Report generated by RAGking v2.1",
        "excellent":          "Excellent",
        "good":               "Good",
        "acceptable":         "Acceptable",
        "needs_improvement":  "Needs Improvement",
        "per_q":              "PER-QUESTION METRICS (COMPACT)",
        "tok_eff_note":       "TokEff = Total Tokens / max(Correctness, 1). Lower is better.",
        "interp_excellent":   "The RAG system demonstrates solid overall performance.",
        "interp_good":        "The RAG system performs well with a balanced profile.",
        "interp_acceptable":  "The system works but still needs optimization in key dimensions.",
        "interp_poor":        "The system needs significant improvements in one or more areas.",
    },
}

# Path to the pre-rendered formulas image.
_THIS_FILE = Path(__file__).resolve()
FORMULAS_IMAGE_PATH = _THIS_FILE.parents[1] / "formulas" / "formulas.png"


def _formula_image_flowable():
    if FORMULAS_IMAGE_PATH.exists():
        formula_art = Image(str(FORMULAS_IMAGE_PATH))
        formula_art.hAlign = "CENTER"
        formula_art.drawWidth = formula_art.imageWidth * 0.75
        formula_art.drawHeight = formula_art.imageHeight * 0.75
        return formula_art
    return None

LABEL_TO_INTERP_KEY = {
    "Excellent":         "interp_excellent",
    "Good":              "interp_good",
    "Acceptable":        "interp_acceptable",
    "Needs Improvement": "interp_poor",
}


# ══════════════════════════════════════════════════════════════════════════════
#  STYLE HELPERS
# ══════════════════════════════════════════════════════════════════════════════
def _styles():
    base = getSampleStyleSheet()
    title_s = ParagraphStyle("CTitle", parent=base["Heading1"],
                             fontSize=22, textColor=colors.HexColor("#2c3e50"),
                             spaceAfter=6, alignment=TA_CENTER, fontName="Helvetica-Bold")
    head_s  = ParagraphStyle("CHead",  parent=base["Heading2"],
                             fontSize=13, textColor=colors.HexColor("#34495e"),
                             spaceAfter=10, spaceBefore=10, fontName="Helvetica-Bold")
    cell_s  = ParagraphStyle("CCell",  parent=base["Normal"],
                             fontName="Helvetica", fontSize=8.5, leading=10, alignment=TA_LEFT)
    hdr_s   = ParagraphStyle("CHdr",   parent=base["Normal"],
                             fontName="Helvetica-Bold", fontSize=9, leading=11,
                             textColor=colors.whitesmoke, alignment=TA_CENTER)
    score_s = ParagraphStyle("CScore", parent=base["Normal"],
                             fontName="Helvetica-Bold", fontSize=14, leading=16,
                             textColor=colors.whitesmoke, alignment=TA_CENTER)
    compact_s = ParagraphStyle("CCompact", parent=cell_s,
                               fontSize=7, leading=8, alignment=TA_CENTER)
    compact_h = ParagraphStyle("CCompactH", parent=hdr_s, fontSize=7.5, leading=9)
    return base, title_s, head_s, cell_s, hdr_s, score_s, compact_s, compact_h


def _P(text, style):
    return Paragraph(str(text), style)


def _safe_text(value, max_len=None):
    s = "" if value is None else str(value)
    s = s.replace("\r\n", "\n").replace("\r", "\n")
    if max_len and len(s) > max_len:
        s = s[: max_len - 1] + "…"
    s = xml_escape(s)
    return s.replace("\n", "<br/>")


_DARK  = colors.HexColor("#34495e")
_LIGHT = colors.HexColor("#ecf0f1")

_BASE_TABLE_STYLE = TableStyle([
    ("BACKGROUND",   (0, 0), (-1,  0), _DARK),
    ("ALIGN",        (0, 0), (-1, -1), "LEFT"),
    ("LEFTPADDING",  (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING",   (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
    ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ("GRID",         (0, 0), (-1, -1), 1, colors.grey),
    ("ROWBACKGROUNDS",(0, 1),(-1, -1), [colors.white, _LIGHT]),
])


# ══════════════════════════════════════════════════════════════════════════════
#  SINGLE-DATASET PDF REPORT
# ══════════════════════════════════════════════════════════════════════════════
def generate_pdf_report(
    results_df: pd.DataFrame,
    output_path: str,
    operational_factors: dict = None,
    report_lang: str = "en",
    failure_count_override: int = None,
) -> bool:
    info("Generating PDF report...")
    time.sleep(0.2)

    # temporary files prefix for plots/images
    _TMP = "/tmp/ragking_"
    report_lang = (report_lang or "en").lower()
    if report_lang not in REPORT_TEXT:
        report_lang = "en"
    R  = REPORT_TEXT[report_lang]
    w  = state["weights"]
    c  = state["llm"]

    base, title_s, head_s, cell_s, hdr_s, score_s, compact_s, compact_h = _styles()

    def P(text, style=None):
        return _P(text, style or cell_s)

    doc   = SimpleDocTemplate(output_path, pagesize=letter,
                              topMargin=0.5*inch, bottomMargin=0.5*inch)
    story = []

    # ── Cover ────────────────────────────────────────────────────────────────
    story += [
        Spacer(1, 0.4*inch),
        _P(R["title"],    title_s),
        _P(R["subtitle"], base["Normal"]),
        Spacer(1, 0.3*inch),
        _P(f"<i>{R['generated']}: {datetime.now().strftime('%B %d, %Y · %H:%M')}</i>", base["Normal"]),
        Spacer(1, 0.5*inch),
    ]

    # ── Overall Score ─────────────────────────────────────────────────────────
    overall_score = results_df["RAGking_score"].mean()
    overall_label = get_score_label(overall_score)
    label_map = {
        "Excellent": R["excellent"], "Good": R["good"],
        "Acceptable": R["acceptable"], "Needs Improvement": R["needs_improvement"],
    }
    overall_label_text = label_map.get(overall_label, overall_label)
    interp_key = LABEL_TO_INTERP_KEY.get(overall_label, "interp_acceptable")

    story.append(_P(R["overall"], head_s))
    sc_tbl = Table(
        [[_P(f"{overall_score:.2f}/100", score_s), _P(overall_label_text, score_s)]],
        colWidths=[3.4*inch, 3.4*inch],
    )
    sc_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), rl_score_color(overall_score)),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING",    (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("BOX",           (0, 0), (-1, -1), 2, _DARK),
    ]))
    story += [sc_tbl, Spacer(1, 0.2*inch),
              _P(f"<b>{R['interpretation']}:</b> {R[interp_key]}", base["Normal"]),
              Spacer(1, 0.3*inch)]

    # ── Key Metrics ───────────────────────────────────────────────────────────
    if failure_count_override is not None:
        fail_rate = min(max(float(failure_count_override) / max(len(results_df), 1), 0.0), 1.0)
    else:
        fail_rate = float(results_df["is_failure"].sum()) / max(len(results_df), 1)

    story.append(_P(R["metrics"], head_s))
    story.append(_P("FORMULAS USED", ParagraphStyle("FHead", parent=base["Normal"], fontName="Helvetica-Bold", fontSize=10, spaceBefore=6)))
    formula_art = _formula_image_flowable()
    if formula_art is not None:
        story.append(formula_art)
        story.append(Spacer(1, 0.15*inch))
    else:
        fstyle = ParagraphStyle("Formula", parent=base["Normal"], fontName="Courier", fontSize=9, leading=12)
        story.append(Preformatted("RAGking = (wC · C_norm + wE · E_norm + wL · L_norm + wM · M_norm + wF · F_norm) × 100", fstyle))
        story.append(Spacer(1, 0.06*inch))
        story.append(Preformatted("Cost per query = (PromptTokens / 1e6) · Input$/1M + (CompletionTokens / 1e6) · Output$/1M", fstyle))
        story.append(Spacer(1, 0.06*inch))
        story.append(Preformatted("Economic Efficiency = Correctness / Cost_per_query  (Correctness per USD)", fstyle))
        story.append(Spacer(1, 0.06*inch))
        story.append(Preformatted("Token Efficiency = (PromptTokens + CompletionTokens) / max(Correctness, 1)", fstyle))
        story.append(Spacer(1, 0.12*inch))

    metrics_rows = [
        [P(R["metric"], hdr_s), P(R["value"], hdr_s), P(R["observation"], hdr_s)],
        [P(R["samples"]),          P(str(len(results_df))),                        P("Total evaluated queries")],
        [P(R["correctness_avg"]),  P(f"{results_df['Correctness'].mean():.2f}/5"), P("LLM-as-a-Judge score")],
        [P(R["latency_avg"]),      P(f"{results_df['Execution Time (ms)'].mean():.1f} ms"), P("Average response time")],
        [P("Avg cost per query (USD)"), P(f"${results_df['cost_per_query'].mean():.6f}"), P("Average API cost per single query")],
        [P("Economic Efficiency (Correctness/USD)"), P(f"{results_df['economic_eff_raw'].mean():.4f}"), P("Correctness per USD (mean)")],
        [P("Token Efficiency (tok/pt)"), P(f"{results_df['token_eff_raw'].mean():.2f}"), P("(Prompt + Completion) / max(Correctness, 1), lower is better")],
        [P(R["prompt_tokens_avg"]),P(f"{results_df['Prompt Tokens'].mean():.0f}"),          P("Average prompt tokens")],
        [P(R["completion_tokens_avg"]), P(f"{results_df['Completion Tokens'].mean():.0f}"), P("Average completion tokens")],
        [P(R["total_tokens_avg"]), P(f"{results_df['Total Tokens'].mean():.0f}"),           P("Average total tokens")],
        [P(R["sim_avg"]),          P(f"{results_df['String Similarity'].mean():.3f}"),      P("Mean similarity vs expected")],
        [P(R["fail_rate"]),        P(f"{fail_rate * 100:.1f}%"),                            P("Empty/invalid response ratio")],
        [P(R["std"]),              P(f"{results_df['RAGking_score'].std():.2f}"),            P("Performance variability")],
    ]
    mt = Table(metrics_rows, colWidths=[2.2*inch, 1.3*inch, 3.8*inch], repeatRows=1)
    mt.setStyle(_BASE_TABLE_STYLE)
    story += [mt, Spacer(1, 0.12*inch)]

    # If there is a global operational factor, surface it early in the report
    if operational_factors and "__global__" in operational_factors:
        g = operational_factors["__global__"]
        try:
            g_desc = f"Global — Deploy: {g['deploy_hours']}h | Difficulty: {g['difficulty']}/5 | Maint: {g['maintenance_hours_week']}h/wk"
        except Exception:
            # Fallback: stringify the entry
            g_desc = str(g)
        story.append(_P("<b>Global operational factors:</b>", base["Normal"]))
        story.append(_P(g_desc, base["Normal"]))
        story.append(Spacer(1, 0.2*inch))

    # ── Per-question compact table ────────────────────────────────────────────
    story.append(_P(R["per_q"], head_s))
    story.append(_P(f"<i>{R['tok_eff_note']}</i>", base["Normal"]))
    story.append(Spacer(1, 0.1*inch))

    metric_cols = [
        "Prompt Tokens", "Completion Tokens", "Total Tokens",
        "Execution Time (ms)", "Correctness", "String Similarity",
        "cost_per_query", "economic_eff_raw", "token_eff_raw",
    ]
    short = {"Prompt Tokens":"P","Completion Tokens":"Comp","Total Tokens":"Tok",
             "Execution Time (ms)":"Time","Correctness":"Corr",
             "String Similarity":"Sim","cost_per_query":"Cost","economic_eff_raw":"Econ","token_eff_raw":"TokEff"}

    def fmt(col, v):
        if v is None: return ""
        try:
            if pd.isna(v): return ""
        except Exception: pass
        if isinstance(v, (bool, np.bool_)): return "1" if bool(v) else "0"
        if col in {"Prompt Tokens","Completion Tokens","Total Tokens"}:
            return str(int(float(v)))
        if col == "Execution Time (ms)": return f"{float(v):.0f}"
        if col == "Correctness":
            fv = float(v); return f"{fv:.0f}" if abs(fv - round(fv)) < 1e-6 else f"{fv:.1f}"
        if col == "String Similarity": return f"{float(v):.3f}"
        if col == "cost_per_query": return f"${float(v):.6f}"
        if col == "economic_eff_raw": return f"{float(v):.4f}"
        if col == "token_eff_raw": return f"{float(v):.2f}"
        try:
            fv = float(v); return f"{fv:.3f}" if abs(fv) < 1 else f"{fv:.2f}"
        except Exception: return str(v)

    hdr = [_P("Q", compact_h)] + [_P(short.get(metric_name, metric_name), compact_h) for metric_name in metric_cols]
    pq_rows = [hdr]
    for i, row in results_df.reset_index(drop=True).iterrows():
        cells = [_P(f"q{i+1}", compact_s)]
        for metric_name in metric_cols:
            cells.append(_P(_safe_text(fmt(metric_name, row.get(metric_name, "")), max_len=32), compact_s))
        pq_rows.append(cells)

    q_w = 0.45*inch
    col_w = (7.5*inch - q_w) / len(metric_cols)
    pq_tbl = Table(pq_rows, colWidths=[q_w] + [col_w]*len(metric_cols), repeatRows=1)
    pq_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1,  0), _DARK),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.grey),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 2),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 2),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, _LIGHT]),
    ]))
    story += [pq_tbl, PageBreak()]

    # ── Dashboard ─────────────────────────────────────────────────────────────
    story.append(_P("DETAILED METRICS ANALYSIS", head_s))
    dash_path = _TMP + "dashboard.png"
    plot_dashboard(results_df, dash_path)
    try:
        story.append(Image(dash_path, width=7.5*inch, height=5.5*inch))
    except Exception as e:
        story.append(_P(f"<i>Error loading dashboard: {e}</i>", base["Normal"]))
    story.append(PageBreak())

    # ── Individual distributions ──────────────────────────────────────────────
    story.append(_P("INDIVIDUAL DISTRIBUTIONS", head_s))
    for col, label, color in [
        ("Correctness",        "Correctness Score [1–5]", "#2ecc71"),
        ("Execution Time (ms)","Latency (ms)",            "#f39c12"),
    ]:
        p = _TMP + f"dist_{col.replace(' ','_')}.png"
        plot_distribution(results_df[col], p, xlabel=label, color=color)
        try:
            story.append(Image(p, width=6.5*inch, height=3.5*inch))
            story.append(Spacer(1, 0.2*inch))
        except Exception: pass
    story.append(PageBreak())

    # ── Model comparison (if applicable) ─────────────────────────────────────
    if "Model" in results_df.columns and len(results_df["Model"].unique()) > 1:
        story.append(_P("MODEL COMPARISON", head_s))
        cmp_path = _TMP + "model_cmp.png"
        plot_model_comparison(results_df, cmp_path)
        try:
            story.append(Image(cmp_path, width=7*inch, height=4*inch))
        except Exception: pass
        story.append(PageBreak())

    # ── Config & Weights ─────────────────────────────────────────────────────
    story.append(_P(R["system_config"], head_s))
    cfg_rows = [
        [P(R["parameter"], hdr_s), P(R["value"], hdr_s)],
        [P("LLM Model (Response)"), P(c["response_model"])],
        [P("LLM Model (Judge)"),    P(c.get("judge_model", ""))],
        [P("Embedding Model"),      P(c["embedding_model"])],
        [P("Response cost (per 1K tokens)"), P(f"${c.get('response_cost_per_1k', 0.0):.6f}")],
        [P("Input cost (per 1M tokens)"),   P(f"${c.get('input_cost_per_1m', 0.0):.6f}")],
        [P("Output cost (per 1M tokens)"),  P(f"${c.get('output_cost_per_1m', 0.0):.6f}")],
        [P("Weight Correctness (wC)"),     P(f"{w['correctness']:.2f}")],
        [P("Weight Economic Eff. (wE)"),P(f"{w.get('economic', w.get('token_eff', 0.0)):.2f}")],
        [P("Weight Latency (wL)"),         P(f"{w['latency']:.2f}")],
        [P("Weight Maintenance (wM)"),     P(f"{w['maintenance']:.2f}")],
        [P("Weight Failure Rate (wF)"),    P(f"{w['failure']:.2f}")],
    ]
    if operational_factors:
        cfg_rows.append([P("Operational Factors"), P("")])
        for k, v in operational_factors.items():
            lbl = k if k != "__global__" else "Global"
            desc = f"Deploy: {v['deploy_hours']}h | Difficulty: {v['difficulty']}/5 | Maint: {v['maintenance_hours_week']}h/wk"
            cfg_rows.append([P(lbl), P(desc)])

    cfg_tbl = Table(cfg_rows, colWidths=[2.8*inch, 4.0*inch], repeatRows=1)
    cfg_tbl.setStyle(_BASE_TABLE_STYLE)
    # Note: RAGking formula is shown earlier under 'FORMULAS USED' — avoid duplicate here
    story += [cfg_tbl, Spacer(1, 0.3*inch), PageBreak()]

    # ── Recommendations ───────────────────────────────────────────────────────
    story.append(_P(R["analysis"], head_s))
    c_mean = results_df["Correctness"].mean()
    l_mean = results_df["Execution Time (ms)"].mean()
    s_mean = results_df["String Similarity"].mean()
    f_pct  = fail_rate * 100

    story.append(_P(f"<b>{R['strengths']}:</b>", base["Normal"]))
    strengths = []
    if c_mean >= 4.0:   strengths.append(f"• Excellent answer quality: {c_mean:.2f}/5")
    if l_mean < 1000:   strengths.append(f"• Good response time: {l_mean:.0f} ms")
    if s_mean >= 0.75:  strengths.append(f"• High semantic similarity: {s_mean:.3f}")
    if f_pct < 5:       strengths.append(f"• Low failure rate: {f_pct:.1f}%")
    if not strengths:   strengths = ["• The system is operating at an acceptable level"]
    for s in strengths:
        story.append(_P(s, base["Normal"]))

    story.append(Spacer(1, 0.15*inch))
    story.append(_P(f"<b>{R['improvements']}:</b>", base["Normal"]))
    improvements = []
    if c_mean < 3.5:    improvements.append(f"• Improve answer quality: {c_mean:.2f}/5")
    if l_mean > 2000:   improvements.append(f"• Optimize latency: {l_mean:.0f} ms")
    if s_mean < 0.6:    improvements.append(f"• Improve semantic relevance: {s_mean:.3f}")
    if f_pct > 10:      improvements.append(f"• Reduce failure rate: {f_pct:.1f}%")
    if not improvements: improvements = ["• No critical improvement areas detected"]
    for imp in improvements:
        story.append(_P(imp, base["Normal"]))

    story += [
        Spacer(1, 0.3*inch),
        _P(f"<i>{R['report_footer']} · {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</i>",
           base["Normal"]),
    ]

    try:
        doc.build(story)
        ok(f"PDF report  →  {output_path}")
        return True
    except Exception as e:
        err(f"PDF build error: {e}")
        return False


def _export_comparative_table(pdf_path: str, fw_names: list, comp_data: list):
    """Export the FULL COMPARATIVE ANALYSIS table to xlsx and csv formats."""
    import os
    from pathlib import Path
    
    # Derive output paths from PDF path
    pdf_dir = os.path.dirname(pdf_path)
    pdf_stem = Path(pdf_path).stem
    xlsx_path = os.path.join(pdf_dir, f"{pdf_stem}_FULL_COMPARATIVE_ANALYSIS.xlsx")
    csv_path = os.path.join(pdf_dir, f"{pdf_stem}_FULL_COMPARATIVE_ANALYSIS.csv")
    
    # Build DataFrame from comp_data
    rows_list = []
    for dimension, metric, values, diff_type in comp_data:
        row_dict = {
            "Dimension": dimension,
            "Metric": metric,
        }
        for i, fw_name in enumerate(fw_names):
            v = values[i] if i < len(values) else None
            if v is None:
                row_dict[fw_name] = ""
            elif isinstance(v, (int, float)):
                row_dict[fw_name] = round(v, 4) if isinstance(v, float) else v
            else:
                row_dict[fw_name] = str(v)
        rows_list.append(row_dict)
    
    df = pd.DataFrame(rows_list)
    
    # Export to xlsx
    try:
        df.to_excel(xlsx_path, sheet_name="Comparative Analysis", index=False)
        ok(f"Comparative table exported  →  {xlsx_path}")
    except Exception as e:
        err(f"XLSX export failed: {e}")
    
    # Export to csv
    try:
        df.to_csv(csv_path, index=False)
        ok(f"Comparative table exported  →  {csv_path}")
    except Exception as e:
        err(f"CSV export failed: {e}")


# ══════════════════════════════════════════════════════════════════════════════
#  MULTI-FRAMEWORK COMPARISON PDF REPORT
# ══════════════════════════════════════════════════════════════════════════════
def generate_framework_pdf(
    frameworks: dict,
    output_path: str,
    report_lang: str = "en",
) -> bool:

    info("Generating framework comparison PDF...")
    time.sleep(0.2)

    _TMP = "/tmp/ragking_"

    report_lang = (report_lang or "en").lower()
    if report_lang not in REPORT_TEXT:
        report_lang = "en"

    R = REPORT_TEXT[report_lang]
    c = state["llm"]

    base, title_s, head_s, cell_s, hdr_s, score_s, compact_s, compact_h = _styles()

    def P(text, style=None):
        return _P(text, style or cell_s)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )

    story = []

    # ─────────────────────────────────────────
    # COVER
    # ─────────────────────────────────────────
    story += [
        Spacer(1, 0.4*inch),
        _P("RAG FRAMEWORK COMPARISON REPORT", title_s),
        _P("RAGking v2.1 - Multi-Framework Analysis", base["Normal"]),
        Spacer(1, 0.3*inch),
        _P(f"<i>{R['generated']}: {datetime.now().strftime('%B %d, %Y · %H:%M')}</i>", base["Normal"]),
        Spacer(1, 0.5*inch),
        _P(
            f"Frameworks compared: <b>{len(frameworks)}</b> — " +
            ", ".join(f"<b>{n}</b>" for n in frameworks),
            base["Normal"]
        ),
        Spacer(1, 0.4*inch),
    ]

    # ─────────────────────────────────────────
    # SUMMARY - EXPLANATION TABLE (VERTICAL)
    # ─────────────────────────────────────────
    story.append(_P("FRAMEWORK SUMMARY - METRIC DEFINITIONS", head_s))

    story.append(_P("FORMULAS USED", ParagraphStyle("FHeadFW", parent=base["Normal"], fontName="Helvetica-Bold", fontSize=10, spaceBefore=6)))
    formula_art = _formula_image_flowable()
    if formula_art is not None:
        story.append(formula_art)
        story.append(Spacer(1, 0.15*inch))
    else:
        fstyle_fw = ParagraphStyle("FormulaFW", parent=base["Normal"], fontName="Courier", fontSize=9, leading=12)
        story.append(Preformatted("RAGking = (wC · C_norm + wE · E_norm + wL · L_norm + wM · M_norm + wF · F_norm) × 100", fstyle_fw))
        story.append(Spacer(1, 0.06*inch))
        story.append(Preformatted("Cost per query = (AvgPrompt / 1e6) · Input$/1M + (AvgCompletion / 1e6) · Output$/1M", fstyle_fw))
        story.append(Spacer(1, 0.06*inch))
        story.append(Preformatted("Economic Efficiency (Correctness/USD) = Correctness_mean / Cost_per_query", fstyle_fw))
        story.append(Spacer(1, 0.06*inch))
        story.append(Preformatted("Token Efficiency (tok/pt) = (AvgPrompt + AvgCompletion) / max(Correctness_mean, 1)", fstyle_fw))
        story.append(Spacer(1, 0.06*inch))
        story.append(Preformatted("Difference semantics: % change uses V1 = highest value", fstyle_fw))
        story.append(Preformatted("Failure rates and Level counts use absolute differences", fstyle_fw))
        story.append(Spacer(1, 0.12*inch))

    expl_rows = [
        [P("<b>Metric</b>", hdr_s), P("<b>Description</b>", hdr_s), P("<b>Unit</b>", hdr_s)],
        [P("RAGking Score", cell_s), P("Composite ranking score combining all performance dimensions", cell_s), P("[0–100]", cell_s)],
        [P("Correctness", cell_s), P("LLM-as-a-Judge score measuring answer quality", cell_s), P("[1–5]", cell_s)],
        [P("Latency", cell_s), P("Average response time from query to answer", cell_s), P("[ms]", cell_s)],
        [P("Similarity", cell_s), P("Cosine similarity between generated and expected answers", cell_s), P("[0–1]", cell_s)],
        [P("Failure Rate", cell_s), P("Percentage of invalid or empty responses", cell_s), P("[%]", cell_s)],
        [P("Token Efficiency", cell_s), P("Total tokens consumed per correctness point (↓ better)", cell_s), P("[tok/pt]", cell_s)],
        [P("Std Dev", cell_s), P("Standard deviation of RAGking Score (↓ better)", cell_s), P("[score]", cell_s)],
        [P("Prompt Tokens", cell_s), P("Average number of input tokens per query", cell_s), P("[tokens]", cell_s)],
        [P("Completion Tokens", cell_s), P("Average number of output tokens per response", cell_s), P("[tokens]", cell_s)],
        [P("Total Tokens", cell_s), P("Sum of prompt and completion tokens", cell_s), P("[tokens]", cell_s)],
        [P("Deploy Time", cell_s), P("Estimated hours to setup and deploy", cell_s), P("[hours]", cell_s)],
        [P("Difficulty", cell_s), P("Implementation complexity rating", cell_s), P("[1–5]", cell_s)],
        [P("Maintenance", cell_s), P("Weekly maintenance effort required", cell_s), P("[h/week]", cell_s)],
    ]

    expl_tbl = Table(expl_rows, colWidths=[1.5*inch, 4.0*inch, 1.3*inch], repeatRows=1)
    expl_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ALIGN", (0, 2), (2, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT]),
    ]))
    story += [Spacer(1, 0.15*inch), expl_tbl, PageBreak()]

    # ─────────────────────────────────────────
    # COMPREHENSIVE COMPARISON TABLE WITH DIFFERENCES
    # ─────────────────────────────────────────
    story.append(_P("FULL COMPARATIVE ANALYSIS", head_s))

    frameworks_list = list(frameworks.items())
    fw_names = [name for name, _ in frameworks_list]

    # Helper function to categorize correctness levels
    def get_response_levels(df):
        levels = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}
        for corr in df["Correctness"]:
            if corr <= 1.0:
                levels[1] += 1
            elif corr <= 2.0:
                levels[2] += 1
            elif corr <= 3.0:
                levels[3] += 1
            elif corr <= 4.0:
                levels[4] += 1
            else:
                levels[5] += 1
        return levels

    # Calculate percentage variation taking V1 as the highest value.
    def calc_diff(values):
        nums = []
        for value in values:
            if value is None:
                continue
            try:
                nums.append(float(value))
            except Exception:
                continue

        if len(nums) < 2:
            return "—"

        v1 = max(nums)
        if v1 == 0:
            return "—"

        # For 2 frameworks this is the other value; for N frameworks this uses the minimum.
        v2 = min(nums)
        pct_change = ((v2 - v1) / v1) * 100
        return f"{pct_change:.2f}%"

    def calc_abs_diff(values, decimals=2):
        nums = []
        for value in values:
            if value is None:
                continue
            try:
                nums.append(float(value))
            except Exception:
                continue

        if len(nums) < 2:
            return "—"

        highest = max(nums)
        lowest = min(nums)
        diff = lowest - highest
        return f"{diff:.{decimals}f}"

    def framework_failure_rate_percent(df: pd.DataFrame) -> float:
        """Return failure rate in percent using robust column parsing."""
        if "failure_rate" in df.columns:
            fr = pd.to_numeric(df["failure_rate"], errors="coerce").fillna(0.0)
            # If the source is already in percent, normalize to [0,1] before converting.
            if float(fr.max()) > 1.0:
                fr = fr / 100.0
            return float(fr.mean()) * 100.0

        if "is_failure" in df.columns:
            raw = df["is_failure"]
            bool_series = raw.astype(str).str.strip().str.lower().map({
                "1": True, "true": True, "t": True, "yes": True, "y": True,
                "si": True, "sí": True, "fail": True, "failed": True, "failure": True,
                "0": False, "false": False, "f": False, "no": False, "n": False,
                "ok": False, "success": False, "passed": False, "pass": False, "": False,
            })
            num_series = pd.to_numeric(raw, errors="coerce").map(
                lambda x: np.nan if pd.isna(x) else bool(int(x))
            )
            parsed = bool_series.where(bool_series.notna(), num_series).fillna(False).astype(bool)
            return float(parsed.mean()) * 100.0

        return 0.0

    # Build comprehensive rows with dimensions and metrics
    comp_data = []

    # Token consumption section
    comp_data.append(("Token Consumption", "Prompt tokens (avg.)", 
                     [frameworks[n]["Prompt Tokens"].mean() for n in fw_names], "percentage"))
    comp_data.append(("Token Consumption", "Completion tokens (avg.)", 
                     [frameworks[n]["Completion Tokens"].mean() for n in fw_names], "percentage"))
    comp_data.append(("Token Consumption", "Total tokens (avg.)", 
                     [frameworks[n]["Total Tokens"].mean() for n in fw_names], "percentage"))
    comp_data.append(("Token Consumption", "Economic Efficiency (Correctness/USD)", 
                     [frameworks[n]["economic_eff_raw"].mean() for n in fw_names], "points"))
    comp_data.append(("Token Consumption", "Token Efficiency (tok/pt)", 
                     [frameworks[n]["token_eff_raw"].mean() for n in fw_names], "points"))

    # Latency section
    comp_data.append(("Latency", "Execution time (ms)", 
                     [frameworks[n]["Execution Time (ms)"].mean() for n in fw_names], "percentage"))

    # Response quality section
    comp_data.append(("Response Quality", "RAGking Overall Score", 
                     [frameworks[n]["RAGking_score"].mean() for n in fw_names], "points"))
    comp_data.append(("Response Quality", "Std. Dev. (RAGking Score)", 
                     [frameworks[n]["RAGking_score"].std() for n in fw_names], "points"))
    comp_data.append(("Response Quality", "Avg. correctness score", 
                     [frameworks[n]["Correctness"].mean() for n in fw_names], "points"))
    comp_data.append(("Response Quality", "Cosine similarity (avg.)", 
                     [frameworks[n]["String Similarity"].mean() for n in fw_names], "value"))
    comp_data.append(("Response Quality", "Failure rate", 
                     [framework_failure_rate_percent(frameworks[n]) for n in fw_names], "absolute"))

    # Response level distribution
    for level in [1, 2, 3, 4, 5]:
        comp_data.append(("Response Quality", f"Level {level} responses", 
                         [get_response_levels(frameworks[n])[level] for n in fw_names], "absolute_int"))

    # Deployment / maintenance section
    comp_data.append(("Deployment", "Deploy Time (hours)",
                     [frameworks[n]["deploy_hours"].mean() if "deploy_hours" in frameworks[n].columns else None for n in fw_names], "absolute"))
    comp_data.append(("Deployment", "Difficulty (1-5)",
                     [frameworks[n]["implementation_difficulty"].mean() if "implementation_difficulty" in frameworks[n].columns else None for n in fw_names], "absolute"))
    comp_data.append(("Deployment", "Maintenance (h/week)",
                     [frameworks[n]["maintenance_hours_week"].mean() if "maintenance_hours_week" in frameworks[n].columns else None for n in fw_names], "absolute"))

    # Define which metrics maximize (True) vs minimize (False) for best value highlighting
    metric_optimization = {
        # Maximize
        "RAGking Overall Score": True,
        "Avg. correctness score": True,
        "Cosine similarity (avg.)": True,
        "Economic Efficiency (Correctness/USD)": True,
        "Level 3 responses": True,
        "Level 4 responses": True,
        "Level 5 responses": True,
        # Minimize
        "Prompt tokens (avg.)": False,
        "Completion tokens (avg.)": False,
        "Total tokens (avg.)": False,
        "Token Efficiency (tok/pt)": False,
        "Execution time (ms)": False,
        "Std. Dev. (RAGking Score)": False,
        "Failure rate": False,
        "Per 1,000 queries": False,
        "Level 1 responses": False,
        "Level 2 responses": False,
        # Minimize also (lower is better)
        "Deploy Time (hours)": False,
        "Difficulty (1-5)": False,
        "Maintenance (h/week)": False,
    }

    # Build table rows: Dimension | Metric | Framework1 | Framework2 | ... | Difference
    comp_rows = []
    header_texts = ["Dimension", "Metric"] + fw_names + ["Difference / Note"]
    comp_rows.append([P(f"<b>{t}</b>", hdr_s) for t in header_texts])

    # Track which cells should be highlighted (for TableStyle later)
    best_cells = []

    for dimension, metric, values, diff_type in comp_data:
        row = [P(dimension, cell_s), P(metric, cell_s)]
        
        # Determine best value index for highlighting
        best_idx = -1
        if diff_type not in ["none", "text"] and metric in metric_optimization:
            # build numeric list preserving None for non-numeric
            numeric_values = []
            for v in values:
                try:
                    numeric_values.append(float(v))
                except Exception:
                    numeric_values.append(None)

            valid_pairs = [(i, numeric_values[i]) for i in range(len(numeric_values)) if numeric_values[i] is not None]
            if valid_pairs:
                maximize = metric_optimization.get(metric, True)
                if maximize:
                    best_idx = max(valid_pairs, key=lambda x: x[1])[0]
                else:
                    best_idx = min(valid_pairs, key=lambda x: x[1])[0]
        
        # Add framework values
        for i, v in enumerate(values):
            if v is None:
                row.append(P("", cell_s))
            elif isinstance(v, str):
                row.append(P(v, cell_s))
            elif metric == "Pricing (DeepSeek R1): $0.55/1M Input | $2.19/1M Output":
                row.append(P("", cell_s))
            elif "%" in metric and isinstance(v, float) and v < 100:
                row.append(P(f"{v:.1f}%", cell_s))
            elif diff_type == "text" or "complexity" in metric.lower() or "profile" in metric.lower():
                row.append(P(str(v), cell_s))
            else:
                # Numeric values
                if isinstance(v, int):
                    row.append(P(f"{v:,}", cell_s))
                elif metric == "Token Efficiency (tok/pt)":
                    row.append(P(f"{v:.2f}", cell_s))
                elif v > 100 or (metric and "Token" in metric):
                    row.append(P(f"{v:,.0f}", cell_s))
                elif v > 10:
                    row.append(P(f"{v:.1f}", cell_s))
                else:
                    row.append(P(f"{v:.2f}", cell_s))
            
            # Mark cell for highlighting if it's the best
            if i == best_idx:
                best_cells.append((len(comp_rows), 2 + i))  # Row index, column index
        
        # Add difference as % variation (V1 = highest value), except absolute rows requested.
        if diff_type == "none" or diff_type == "text":
            diff_str = ""
        elif diff_type == "absolute":
            diff_str = calc_abs_diff(values, decimals=1)
        elif diff_type == "absolute_int":
            diff_str = calc_abs_diff(values, decimals=0)
        else:
            diff_str = calc_diff(values)
        
        row.append(P(diff_str, cell_s))
        comp_rows.append(row)

    # Calculate column widths - adjustable based on number of frameworks
    n_fw = len(fw_names)
    dim_w = 1.2 * inch
    metric_w = 1.8 * inch
    fw_w = (7.5 * inch - dim_w - metric_w - 1.0 * inch) / n_fw if n_fw > 0 else 1.5 * inch
    diff_w = 1.0 * inch

    comp_tbl = Table(comp_rows, colWidths=[dim_w, metric_w] + [fw_w] * n_fw + [diff_w], repeatRows=1)

    comp_tbl.setStyle(TableStyle([
        # Header styling
        ("BACKGROUND", (0, 0), (-1, 0), _DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        
        # Data row styling - NO background for readability
        ("BACKGROUND", (0, 1), (-1, -1), colors.white),
        ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),
        
        # Dimension column styling
        ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#e8f4f8")),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (-1, -1), 7.5),
        
        # Grid and alignment
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        
        # Padding
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))

    # Apply soft green highlighting to best values
    for row_idx, col_idx in best_cells:
        comp_tbl.setStyle(TableStyle([
            ("BACKGROUND", (col_idx, row_idx), (col_idx, row_idx), colors.HexColor("#d4f1d4")),
        ]))

    story += [Spacer(1, 0.1*inch), comp_tbl, Spacer(1, 0.25*inch), PageBreak()]

    # ─────────────────────────────────────────
    # GRÁFICOS
    # ─────────────────────────────────────────

    # RAGking
    story.append(_P("OVERALL RAGKING SCORES", head_s))
    rk_path = _TMP + "fw_ragking.png"
    plot_framework_ragking_bars(frameworks, rk_path)
    try:
        story.append(Image(rk_path, width=7*inch, height=4.5*inch))
    except:
        pass
    story.append(PageBreak())

    # Multi-metric
    story.append(_P("MULTI-METRIC COMPARISON", head_s))
    grp_path = _TMP + "fw_grouped.png"
    plot_framework_comparison_bars(frameworks, grp_path)
    try:
        story.append(Image(grp_path, width=7.5*inch, height=4.5*inch))
    except:
        pass
    story.append(PageBreak())

    # Spider
    story.append(_P("NORMALIZED METRICS PROFILE", head_s))
    story.append(_P(
        "<i>Normalized [0–1]. Outer = better performance.</i>",
        base["Normal"]
    ))

    sp_path = _TMP + "fw_spider.png"
    plot_framework_spider(frameworks, sp_path)
    try:
        story.append(Image(sp_path, width=6*inch, height=6*inch))
    except:
        pass
    story.append(PageBreak())

    # Boxplots
    story.append(_P("DISTRIBUTION COMPARISON", head_s))

    for col, lbl in [
        ("Correctness", "Correctness"),
        ("Execution Time (ms)", "Latency"),
        ("RAGking_score", "RAGking"),
    ]:
        path = _TMP + f"fw_box_{col.replace(' ','_')}.png"
        plot_framework_box(frameworks, col, lbl, path)

        try:
            story.append(Image(path, width=7*inch, height=3.5*inch))
            story.append(Spacer(1, 0.15*inch))
        except:
            pass

    story.append(PageBreak())

    # ─────────────────────────────────────────
    # FOOTER
    # ─────────────────────────────────────────
    story.append(_P(
        f"<i>RAGking v2.1 · {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</i>",
        base["Normal"]
    ))

    # limpiar pagebreaks extra
    while story and isinstance(story[-1], PageBreak):
        story.pop()

    try:
        doc.build(story)
        ok(f"Framework comparison PDF → {output_path}")
        
        # Export FULL COMPARATIVE ANALYSIS table to xlsx and csv in the same directory
        _export_comparative_table(output_path, fw_names, comp_data)
        
        return True

    except Exception as e:
        err(f"PDF build error: {e}")
        return False